// Generated by ts-to-effect-schema
import * as S from "@effect/schema/Schema";

import * as generated from "./heros.schema";

export type EnemyPower = S.To<typeof generated.enemyPowerSchema>;

export type SkillsSpeedEnemy = S.To<typeof generated.skillsSpeedEnemySchema>;

export type Enemy = S.To<typeof generated.enemySchema>;

export type Superman = S.To<typeof generated.supermanSchema>;

export type Villain = S.To<typeof generated.villainSchema>;

export type Story = S.To<typeof generated.storySchema>;

export type KillSuperman = S.To<typeof generated.killSupermanSchema>;

export type WithDefaults = S.To<typeof generated.withDefaultsSchema>;

export type Exported = S.To<typeof generated.exportedSchema>;

export type GetSupermanSkill = S.To<typeof generated.getSupermanSkillSchema>;

export type HeroContact = S.To<typeof generated.heroContactSchema>;

export type SupermanEnemy = S.To<typeof generated.supermanEnemySchema>;

export type SupermanName = S.To<typeof generated.supermanNameSchema>;

export type SupermanInvinciblePower = S.To<
  typeof generated.supermanInvinciblePowerSchema
>;

export type KrytonResponse = S.To<typeof generated.krytonResponseSchema>;

export type Jim = S.To<typeof generated.jimSchema>;

export type EvilPlan = S.To<typeof generated.evilPlanSchema>;

export type EvilPlanDetails = S.To<typeof generated.evilPlanDetailsSchema>;
