// Generated by ts-to-effect-schema
import * as S from "@effect/schema/Schema";

import * as generated from "./heros.schema";

export type EnemyPower = S.Schema.To<typeof generated.enemyPowerSchema>;

export type SkillsSpeedEnemy = S.Schema.To<
  typeof generated.skillsSpeedEnemySchema
>;

export type Enemy = S.Schema.To<typeof generated.enemySchema>;

export type Superman = S.Schema.To<typeof generated.supermanSchema>;

export type Villain = S.Schema.To<typeof generated.villainSchema>;

export type Story = S.Schema.To<typeof generated.storySchema>;

export type KillSuperman = S.Schema.To<typeof generated.killSupermanSchema>;

export type WithDefaults = S.Schema.To<typeof generated.withDefaultsSchema>;

export type Exported = S.Schema.To<typeof generated.exportedSchema>;

export type GetSupermanSkill = S.Schema.To<
  typeof generated.getSupermanSkillSchema
>;

export type HeroContact = S.Schema.To<typeof generated.heroContactSchema>;

export type SupermanEnemy = S.Schema.To<typeof generated.supermanEnemySchema>;

export type SupermanName = S.Schema.To<typeof generated.supermanNameSchema>;

export type SupermanInvinciblePower = S.Schema.To<
  typeof generated.supermanInvinciblePowerSchema
>;

export type KrytonResponse = S.Schema.To<typeof generated.krytonResponseSchema>;

export type Jim = S.Schema.To<typeof generated.jimSchema>;

export type EvilPlan = S.Schema.To<typeof generated.evilPlanSchema>;

export type EvilPlanDetails = S.Schema.To<
  typeof generated.evilPlanDetailsSchema
>;
