"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.tsToEffectConfigSchema = exports.configsSchema = exports.configSchema = exports.jSDocTagFilterSchema = exports.nameFilterSchema = exports.getSchemaNameSchema = exports.simplifiedJSDocTagSchema = void 0;
const tslib_1 = require("tslib");
// Generated by ts-to-effect-schema
const S = tslib_1.__importStar(require("@effect/schema/Schema"));
const Function_1 = require("@effect/data/Function");
exports.simplifiedJSDocTagSchema = S.struct({
    name: S.string,
    value: S.optional(S.string),
});
exports.getSchemaNameSchema = S.any;
exports.nameFilterSchema = S.any;
exports.jSDocTagFilterSchema = S.any;
exports.configSchema = S.struct({
    input: S.string,
    output: S.string,
    skipValidation: S.optional(S.boolean),
    nameFilter: S.optional(exports.nameFilterSchema),
    jsDocTagFilter: S.optional(exports.jSDocTagFilterSchema),
    getSchemaName: S.optional(exports.getSchemaNameSchema),
    keepComments: S.optional(S.boolean).withDefault(() => false),
    skipParseJSDoc: S.optional(S.boolean).withDefault(() => false),
    inferredTypes: S.optional(S.string),
});
exports.configsSchema = S.array((0, Function_1.pipe)(exports.configSchema, S.extend(S.struct({
    name: S.string,
}))));
exports.tsToEffectConfigSchema = S.union(exports.configSchema, exports.configsSchema);
//# sourceMappingURL=config.schema.js.map